export const statuses = [
    {
		status: 'ACTIVE',
		statusName: 'Active',
		background: '#D8CCF4',
		color: '#6226EF',
		dotColor: '#A46BF5',
		className: 'txt_875',
	},
	{
		status: 'ONGOING',
		statusName: 'Ongoing',
		color: '#000088',
		className: 'txt_875',
	},
	{
		status: 'UPCOMING',
		statusName: 'Upcoming',
		color: '#FFB600',
		className: 'txt_875',
	},
	{
		status: 'CLOSED',
		statusName: 'Closed',
		color: '#C00',
		className: 'txt_875',
	},
	{
		status: 'INCOMPLETE',
		statusName: 'Incomplete',
		color: '#D5700D',
		className: 'txt_875',
	},
	{
		status: 'CHECK_IN',
		statusName: 'Incomplete',
		color: '#D5700D',
		className: 'txt_875',
	},
	{
		status: 'CHECK_OUT',
		statusName: 'Incomplete',
		color: '#D5700D',
		className: 'txt_875',
	},
	{
		status: 'PROCESSED',
		statusName: 'Processed',
		color: '#027A48',
		className: 'txt_875',
	},
	{
		status: 'PENDING',
		statusName: 'Pending',
		background: '#D8CCF4',
		color: '#6226EF',
		dotColor: '#A46BF5',
		className: 'txt_875',
	},
	{
		status: 'SUBMITTED',
		statusName: 'Submited',
		background: '#D8CCF4',
		color: '#6226EF',
		dotColor: '#A46BF5',
		className: 'txt_875',
	},
	{
		status: 'COMPLETED',
		statusName: 'Completed',
		background: '#ECFDF3',
		color: '#027A48',
		dotColor: '#12B76A',
		className: 'txt_875',
	},
	{
		status: 'REJECTED',
		statusName: 'Rejected',
		background: '#F4CFCC',
		color: '#EF3826',
		dotColor: '#E63625',
		className: 'txt_875',
	}, 
	{
		status: 'FAILED',
		statusName: 'Failed',
		background: '#F4CFCC',
		color: '#EF3826',
		dotColor: '#E63625',
		className: 'txt_875',
	}, 
];
